- name: Deploy thedudebridge_app
  hosts: VM-BMS
  gather_facts: false
  tasks:
    - name: clone project
      git:
        repo: https://github.com/muhamadarif085/thedudebridge_devops.git
        dest: /home/engineer/thedudebridge_arif
        force: yes
        update: yes
        version: main

    - name: docker-compose up
      shell: docker-compose up -d
      args:
        chdir: /home/engineer/thedudebridge_arif/thedudebridge

    - name: Jalankan perintah "docker ps"
      shell: docker ps
      register: docker_ps_output

    - name: Tampilkan output dari "docker ps"
      debug:
        var: docker_ps_output.stdout_lines
        
